[#8] [Backend] As a user, I can register an account
mosharaf13/google-scrapper-ruby pull request #28
Opened 2023-05-19 08:03 UTC by mosharaf13

Closes https://github.com/mosharaf13/google-scrapper-ruby/issues/8

## What happened 👀

- Add backend for user registration system.
- Show error message if password doesn't satisfy password requirement (e.g; min 8 chars, uppercase + lowercase + number)
- Redirect to homepage after successful signup

## Insight 📝

- Added devise gem for user authentication.
- Added regex validation to check password complexity

## Proof Of Work 📹

<details>
  <summary>
      - Minimum requirement of 8 chars with mix of uppercase, lowercase, and number
  </summary>
![Screen Shot 2023-05-19 at 2 56 30 PM](https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/e2f981fa-c3db-4b14-b41a-074756973c92)
</details>

<details>
  <summary>
      - Password confirmation must match password field
  </summary>
![Screen Shot 2023-05-19 at 2 55 26 PM](https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/db0557a7-df0b-4068-b836-518fc5c50563)
</details>

<details>
  <summary>
      - Successful sign up 
  </summary>
![Screen Shot 2023-05-19 at 2 56 30 PM](https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/d1cf0d73-81c0-4981-88e7-56cf08ba0d46)
</details>

2023-05-22 02:05 UTC, longnd reviewed
Just a quick first review, I will complete the review this afternoon 🙏
Could you please add a Github .CODEOWNERS file to include Sang, Top, you & I so each of us will receive notification when the PR is ready for review?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

example:
https://github.com/nimblehq/rails-templates/blob/develop/.github/CODEOWNERS

2023-05-22 02:05 UTC, longnd commented on Gemfile
> +gem 'devise'
let's be consistent with other gem
```suggestion
gem 'devise' # Flexible authentication solution for Rails with Warden
```

2023-05-22 02:05 UTC, longnd commented on db/migrate/20230519045115_devise_create_users.rb
> +      t.string :email,              null: false, default: ""
it should use citext data type
https://nimblehq.co/compass/development/web/database/#data-types

2023-05-22 04:17 UTC, sanG-github requested changes
Some first suggestions 🚀

2023-05-22 04:17 UTC, sanG-github commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
As this model will be bigger and bigger as time flies. So, we usually extract these configurations into a Module, and then we can include them back into this model.

```ruby
# models/user.rb
class User < ApplicationRecord
  include Authenticable
end

# models/concerns/authenticable
module Authenticable
  extend ActiveSupport::Concern

  included do
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

    validate :password_complexity, if: :password_required?
  end
end
```

2023-05-22 04:17 UTC, sanG-github commented on app/models/user.rb
> +  end
As we've already checked it with `password_required?`, do you think we need this check? 
Also, we can define the PASSWORD_PATTERN as a constant.
Moreover, we can add a custom `type` for the `error`, and then we can [add the locale for this error](https://guides.rubyonrails.org/v3.2.0/i18n.html#:~:text=For%20example%2C%20you%20might%20have%20an%20Admin%20model%20inheriting%20from%20User%3A) later.

```suggestion
  PASSWORD_PATTERN = /(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}/
  
  def password_complexity
    return if password.match?(PASSWORD_PATTERN)

    errors.add(:password, :invalid)
  end
```

2023-05-22 04:17 UTC, sanG-github commented on app/models/user.rb
> +    !persisted? || password.present? || password_confirmation.present?
Did you mean we should check it when creating the user, right? 🙊 
If yes, we can do it with the `on: :create` [option](https://guides.rubyonrails.org/active_record_callbacks.html#:~:text=Callbacks%20can%20also%20be%20registered%20to%20only%20fire%20on%20certain%20life%20cycle%20events%3A). ✨

2023-05-22 04:17 UTC, sanG-github commented on app/views/home/index.html.erb
> +    Welcome to the world of scrapping!!
Make sure we have the `same indent`, and always have the EOF line. 🚀

2023-05-22 07:55 UTC, mosharaf13 commented on db/migrate/20230519045115_devise_create_users.rb
> +      t.string :email,              null: false, default: ""
Hi @longnd. Thanks for the suggestion 🙏🏼. I have changed the type of email field.

2023-05-22 08:58 UTC, mosharaf13 commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
Do we usually apply this type of module based pattern to other classes as well? e.g. controllers, services. If so, I will keep that in mind next time. Also, if you see any pattern that can be optimized, please feel free to  throw some suggestions 😀 .

2023-05-22 09:14 UTC, mosharaf13 commented on app/models/user.rb
> +  end
Thanks for this great suggestion 👍🏼 . I tried to add this extra checking for password just to see how it's done in rails philosophy. More dirty hands, more learning 😄. Now going with your suggested `:invalid` message. I'll try to add custom validation message later.

2023-05-22 09:32 UTC, mosharaf13 commented on app/models/user.rb
> +    !persisted? || password.present? || password_confirmation.present?
Corrected. I have removed password required actually (look below). Thanks for the suggestion 👍🏼 . Is there any large/standard model file you can suggest me to take a look at from nimble projects?

```
class User < ApplicationRecord
  include Authenticable
  PASSWORD_PATTERN = /(?=.*[A-Z])(?=.*[a-z])(?=.*\d).{8,}/

  before_validation :password_complexity, on: :create

  def password_complexity
    return if password.match?(PASSWORD_PATTERN)

    errors.add(:password, :invalid)
  end
end
```

2023-05-23 05:52 UTC, mosharaf13 commented on app/views/home/index.html.erb
> +    Welcome to the world of scrapping!!
Added. Thanks 👍🏼 . I need to build habit of running `rubocop -A` before a push 😬 .

2023-05-25 04:53 UTC, longnd approved these changes

2023-05-25 10:30 UTC, sanG-github reviewed
Last round of reviews, we're getting there!!! 🚀

2023-05-25 10:30 UTC, sanG-github commented on app/controllers/home_controller.rb
> +  end
We can do it without `render` 🚀 
```suggestion
  def index; end
```

2023-05-25 10:30 UTC, sanG-github commented on app/models/user.rb
> +  def password_complexity
This method must be private, then, no one can access it out of this validation ✨ 

```suggestion
  private
  
  def password_complexity
```

2023-05-25 10:30 UTC, sanG-github commented on app/views/home/index.html.erb
> +</h1>
I added:
- 1 space before for the `<div> Welcome <%= current_user.email %> </div>`
- 1 empty line after the `if else statement`
- Make the `h1` element inline
- EOF (end-of-file)

```suggestion
<% if user_signed_in? %> 
  <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h1> Welcome to the world of scrapping!! </h1>

```

2023-05-25 10:30 UTC, sanG-github commented on config/routes.rb
> +
```suggestion
  root "home#index"

```

2023-05-26 02:53 UTC, mosharaf13 commented on app/views/home/index.html.erb
> +</h1>
Thanks 😀

2023-05-26 07:57 UTC, sanG-github approved these changes

2023-05-26 11:28 UTC, merged