Backend/list keywords
mosharaf13/google-scrapper-ruby pull request #33
Opened 2023-05-23 10:54 UTC by mosharaf13

Closes https://github.com/mosharaf13/google-scrapper-ruby/issues/10
## What happened 👀

- Show list of search stats 
- Add pagination

## Insight 📝

- Used existing gem `pagy` to paginate search stats returned from controller

## Proof Of Work 📹

<details>
 <summary>Pagination links</summary>
<img width="197" alt="Screen Shot 2023-05-23 at 5 49 13 PM" src="https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/09ffb2b1-cba8-478e-a94a-6ed2709b1fc4">
</details>

<details>
 <summary>List of search stats</summary>
<img width="451" alt="Screen Shot 2023-05-23 at 5 48 52 PM" src="https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/bb4e1ef5-11d7-47e3-a112-5430e5929aaf">
</details>

2023-05-25 10:57 UTC, sanG-github requested changes
First round of reviews 🚀

2023-05-25 10:57 UTC, sanG-github commented on .env
>  DOCKER_IMAGE=mosharaf13/google_scrapper_ruby
We should not push this file, as far as I know, this file keeps the secret variables.
So instead of pushing this file, we usually make a copy of this file with the name: `.env.example`.

2023-05-25 10:57 UTC, sanG-github commented on .github/workflows/test.yml
> -
We don't need this change, do we? 🙈

2023-05-25 10:57 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +  include Pagy::Backend
We should better move this one to `ApplicationController`. Then, in other controllers the inherit from the `ApplicationController`, we can use the `Pagy` for pagination without including anything.

2023-05-25 10:57 UTC, sanG-github commented on config/routes.rb
> +  get "/search_stats", to: 'search_stats#index', as: :stats_stats_list
We don't really need this option, or if it's your intention, please share it with us. 🙏 

```suggestion
  get "/search_stats", to: 'search_stats#index'
```

2023-05-25 10:57 UTC, sanG-github commented on app/views/search_stats/_search_stat.html.erb
> +    <strong>Keyword:</strong>
It's time to integrate [I18n](https://guides.rubyonrails.org/i18n.html) 🚀

2023-05-25 10:57 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<p style="color: green"><%= notice %></p>
We don't need this `notice` definition here; we wrap this one with `application.html.erb` as a layout.
(You can take checkout this file)

2023-05-25 10:57 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +  <% end %>
We can render it dynamically ([ref](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections))
```suggestion
  <%= render @search_stats %>
```

2023-05-25 10:58 UTC, sanG-github reviewed
Please remove all the changes related to `Nginx` and `deployment` in this PR as it about keywords list only :wink:

2023-05-26 03:57 UTC, mosharaf13 commented on .env
>  DOCKER_IMAGE=mosharaf13/google_scrapper_ruby
I was looking at [previous ic code](https://github.com/nimblehq/internal-certification-ruby/blob/main/su.v/.env) and saw that .env was pushed. it seemed a bit weird to me too. But I thought let's keep it aligned with previous ic and I pushed it.

I will just add it to .gitignore and push 👍🏼

2023-05-26 04:00 UTC, mosharaf13 commented on .github/workflows/test.yml
> -
Fixed. Thanks for noticing 👍🏼

2023-05-26 04:21 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +  include Pagy::Backend
Nice idea 👍🏼

2023-05-26 05:05 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <strong>Keyword:</strong>
Pushed. Thanks 👍🏼

2023-05-26 05:10 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +<p style="color: green"><%= notice %></p>
Extracted it. Thanks 👍🏼

2023-05-26 05:11 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +  <% end %>
Wow. really convenient. Thanks 👍🏼.

2023-05-26 08:32 UTC, sanG-github requested changes
Please also remove some changes related to `added a new line`, and `removed a line` that does not appropriate to be present in this PR 🙏.

2023-05-26 08:32 UTC, sanG-github commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.keyword %>
We should better wrap it with a `span` tag I guess, to separate the key and the value 🔑 
```suggestion
    <span><%= search_stat.keyword %><span>
```

2023-05-26 08:32 UTC, sanG-github commented on app/views/search_stats/_search_stat.html.erb
> +
```suggestion
```

2023-05-26 08:32 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<h1>Search stats</h1>
We also can use [I18n](https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models:~:text=You%20can%20also%20set%20a%20plural%20form%20for%20model%20names%2C%20adding%20as%20following%3A) to localize the Model name. 🚀

2023-05-26 08:32 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
Missing EOF, but I'm just curious any reason why we need `<%==` instead of `<%=`? 🤔 

>It is important to exercise caution when using the '<%==' tag because it can expose your application to XSS vulnerabilities if you're not careful. Make sure that any content you output using '<%==' has been properly sanitized and does not contain any user-generated or untrusted data.

```suggestion
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

```

2023-05-26 08:32 UTC, sanG-github commented on config/locales/en.yml
> +  search_stat:
Please sort the case in alphabetical order. 🙏

2023-05-26 08:32 UTC, sanG-github commented on config/routes.rb
> +  get "/search_stats", to: 'search_stats#index'
Please take a look at [Rails Routing](https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions). We can keep the current implementation, but it should better follow the Rails Routing as we have `search_stats` as a persisted resource.

```suggestion
  resources :search_stats, only: [:index]
```

2023-05-26 08:32 UTC, sanG-github commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
How about the validation of these fields?

2023-05-26 09:22 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
Sorry, I didn't get it. Like imposing custom lengh, not nullable. Things like that?

2023-05-26 09:24 UTC, mosharaf13 commented
> Please remove all the changes related to `Nginx` and `deployment` in this PR as it about keywords list only 😉

After removing `.env` in this PR, deployment keeps failing (workflow getting empty values). So, I tried to fix workflows by adding different source for .env variables. Should I still remove it?

2023-05-26 09:32 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.keyword %>
I am planning to add these types of changes when I start working on #11. Should I wait for that, or should I work a bit more on view files in this PR.

2023-05-26 09:37 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
[here](https://ddnexus.github.io/pagy/quick-start/#render-the-pagination) it's instructed to use it like that. Should change it?

2023-05-26 09:44 UTC, mosharaf13 commented on config/routes.rb
> +  get "/search_stats", to: 'search_stats#index'
Good idea. It would be better to use the suggested one.

2023-05-26 09:46 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
If you mean validation during insertion, this PR only deals with retrieval 😀

2023-05-26 11:38 UTC, sanG-github commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.keyword %>
Oh sorry, it looks good for the Backend story. 🙏

2023-05-26 11:42 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
We can keep it, as far as I know, it will make two lines below the same functioning 🙏 
Do you have any ideas about it? @longnd 

```ruby
<%= html.html_safe %>
<%== html %>
```

2023-05-29 06:40 UTC, mosharaf13 commented on config/locales/en.yml
> +  search_stat:
Done 👍🏼

2023-05-29 10:23 UTC, sanG-github commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
I mean, should we consider validating these fields at the database layer as well?

2023-05-29 10:26 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<h1>Search stats</h1>
`User.model_name.human` instead of using the title @mosharaf13.
It will be confused between field vs model name. Please help to take a look at the document above again 🙏

2023-05-30 04:10 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +<h1>Search stats</h1>
Fixed

2023-05-30 04:18 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
Yeah, that would be the right to do. Should I create another migration for it or change existing one? I mean, the app isn't yet in production, so no fear of losing data if we run fresh migration again on local.

2023-05-30 04:26 UTC, longnd commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.raw_response %>
Is this a temporary implementation or you plan to show the raw response here, i.e. showing the entire HTML code?
In the latter case, it is better to use iframe to render the result instead.

2023-05-30 04:26 UTC, longnd commented on app/views/search_stats/_search_stat.html.erb
> +    <strong><%= I18n.t('search_stat.keyword')%>:</strong>
if you intend to use I18n, should it be applied for Devise views as well?

2023-05-30 04:26 UTC, longnd commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
for example, this field shoult not be nullable.
also, as we will allow the user to search for keywords, the field should be indexed to improve the query performance

2023-05-30 04:26 UTC, longnd commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.bigint :user_id
shouldn't it be a foreign key to the users table?

2023-05-30 04:26 UTC, longnd commented on spec/fabricators/search_stat_fabricator.rb
> +  keyword            'MyString'
consider using a gem like https://github.com/ffaker/ffaker to generate dummy values

2023-05-30 05:08 UTC, mosharaf13 commented on .github/workflows/test.yml
> +  PORT: ${{secrets.PORT}}
Added static port 80. Thanks 👍🏼 .

2023-05-30 05:09 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.raw_response %>
This is a temporary implementation. I will show raw response in iframe.

2023-05-30 05:12 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <strong><%= I18n.t('search_stat.keyword')%>:</strong>
Yeah, I will be using I18n on Devise views as well.

2023-05-30 05:12 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.bigint :user_id
Yes, it should be. Changing.

2023-05-30 07:06 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.string :keyword
Ok 👍🏼 . Added

2023-05-30 07:25 UTC, mosharaf13 commented on spec/fabricators/search_stat_fabricator.rb
> +  keyword            'MyString'
Added. Thanks 🙏🏼

2023-05-30 10:28 UTC, sanG-github commented on bin/start.sh
> +
I don't know why we still have these changes. 😭 
If you faced any problems, feel free to share them with us @mosharaf13!!!

2023-05-30 10:28 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<h1>Search stats</h1>
Sorry if there's a mismatch, but I don't see any changes related to this comment, could you please provide the commit_id as well? 🙏

2023-05-30 10:38 UTC, sanG-github reviewed
It looks good in overall!!! Also, please help to self review it to revert minor changes 🙏

2023-05-30 10:38 UTC, sanG-github commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.bigint :user_id, null: false
Should it be a [references](https://edgeguides.rubyonrails.org/active_record_migrations.html#references) instead? Not only store the `user_id`, but we also need an index on it. 😄 

```suggestion
      t.references :user, null: false, foreign_key: true
```

2023-05-30 10:38 UTC, sanG-github commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.text :raw_response
Do we need any validations for this field? (such as `null: false`) 😉

2023-05-30 10:55 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +<h1>Search stats</h1>
Fixed in 0cf3347863f0d735af273bc921ab3d443935e22d

2023-05-30 10:55 UTC, mosharaf13 commented on .github/workflows/test.yml
> +  PORT: ${{secrets.PORT}}
Fixed in 8cf9dd3c14c50fe23ee527c4a7414f4f34f06807

2023-05-30 10:57 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <%= search_stat.raw_response %>
Added iframe in 39da3d2ab0adc0f5d96baef23ea32a5628333996 . It's in https://github.com/mosharaf13/google-scrapper-ruby/pull/38/ PR

2023-05-30 10:58 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.bigint :user_id
Fixed in 1d917d1137eecd6ebb1438469eb6539f68958e00

2023-05-30 10:59 UTC, mosharaf13 commented on spec/fabricators/search_stat_fabricator.rb
> +  keyword            'MyString'
Fixed in d84877a38742a0d2089d45bde83472d9bd2476e7

2023-05-30 11:30 UTC, mosharaf13 commented on bin/start.sh
> +
Fixed in baaf1da4d8f4d323e00702c3312ec3011158a4e2.

2023-05-30 11:33 UTC, mosharaf13 commented on bin/start.sh
> +
I usually use `rubocop -A` to fix linting. However, just realized that it doesn't detect/fix double blank lines. Is there any supporting tool available (extension, script) ? or, I should just try to make it a habit 😬

2023-05-30 11:37 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.text :raw_response
Fixed in 6318643c91b3493f8752730f8fb84771e234a8a1

2023-05-30 11:38 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.bigint :user_id, null: false
Fixed in 6318643c91b3493f8752730f8fb84771e234a8a1

2023-05-31 07:21 UTC, sanG-github commented on config/application.yml
> +
```suggestion

```

2023-05-31 07:23 UTC, sanG-github commented on app/models/search_stat.rb
> +end
We need to reflect the database validation in this model. ([ref](https://guides.rubyonrails.org/active_record_validations.html#validation-helpers))

2023-05-31 07:59 UTC, mosharaf13 commented on app/models/search_stat.rb
> +end
Fixed in 284a1f5071a91a471273e1dd0cb61e915d4bebb0

2023-06-01 06:52 UTC, sanG-github commented on bin/start.sh
> +
As this project was forked from the Rails template, we can run this command to check with both `rubocop` and `eslint`

```shell
make codebase/fix
```

2023-06-01 06:56 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +<h1><%= I18n.t('search_stat.title')%></h1>
As I suggested before, we need to add the localization for the Model here.

```suggestion
<h1><%= SearchStat.model_name.human %></h1>
```

```ruby
# config/locales/en.yml
en:
  activerecord:
    models:
      search_stat: Search statistics
```

2023-06-01 07:01 UTC, sanG-github approved these changes
Approved with some last suggestions 🚀

2023-06-01 07:01 UTC, sanG-github commented on db/seeds.rb
> +  Fabricate(:search_stat)
Should it belong to a specific user? Otherwise, it's meaningless to generate these records I guess. 😉

2023-06-01 07:27 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +<h1><%= I18n.t('search_stat.title')%></h1>
Ah okay. I didn't realize you meant this 😬. Fixing ..

2023-06-01 08:05 UTC, mosharaf13 commented on db/seeds.rb
> +  Fabricate(:search_stat)
spec/fabricators/search_stat_fabricator.rb

```
Fabricator(:search_stat) do
  keyword { FFaker::Lorem.word }
  ad_count { rand(1..10) }
  link_count { rand(1..10) }
  total_result_count { rand(1..100) }
  raw_response { FFaker::HTMLIpsum.body }
  user_id { Fabricate(:user).id }
end
```

I am fabricating a new user while creating search stat. For dummy data purposes, shouldn't this be enough?

2023-06-01 10:59 UTC, sanG-github commented on db/seeds.rb
> +  Fabricate(:search_stat)
But where will we use these dummy data? 🤔 
I suggest creating a specific user (login able with  `email` and `password`), then assigning these search stats to this user.

After that, we can log in with this user into the web application and see all the dummy data.

2023-06-01 11:02 UTC, sanG-github commented on app/models/search_stat.rb
> +  validates :raw_response, presence: true
We can validate many fields on the same line.

```suggestion
  belongs_to :user
  
  validates :keyword, :ad_count, :link_count, :total_result_count, :raw_response, presence: true
```

```ruby
    create_table :search_stats do |t|
      t.string :keyword, null: false
      t.integer :ad_count, null: false, default: 0
      t.integer :link_count, null: false, default: 0
      t.bigint :total_result_count, null: false, default: 0
      t.text :raw_response, null: false
      t.references :user, null: false, foreign_key: true

      t.timestamps
    end
```

2023-06-02 02:21 UTC, longnd commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.references :user, null: false, foreign_key: true
Based on the [requirements](https://www.notion.so/nimblehq/Internal-Certification-Path-Web-6a248b20e7c2415086260bbd5958f1c6?pvs=4#96773a3c752849c7802f12516fe00f4f), there are more we need to track:
```
- Number of AdWords advertisers in the top position.
- Total number of AdWords advertisers on the page.
- URLs of the AdWords advertisers in the top position.
- Number of the non-AdWords results on the page.
- URLs of the non-AdWords results on the page.
- Total number of links (all of them) on the page
- HTML code of the page/cache of the page.
```

2023-06-02 02:21 UTC, longnd commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.references :user, null: false, foreign_key: true
also, since the keywords will be process asynchronously, there should be a "status" column to indicate the current status of each keyword, e.g. "Initialized, processing, completed, failed"

2023-06-02 02:21 UTC, longnd commented on app/views/search_stats/index.html.erb
> +<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
I missed this comment.
Those 2 lines are not actually the same @sanG-github c.c @mosharaf13 

`<%== %>` is the alias of raw() method which is a wrapper around `.html_safe()`

https://github.com/rails/rails/blob/96f3c101f1f7a6d920f4675023b4548a1853de53/actionview/lib/action_view/helpers/output_safety_helper.rb#L18-L20
```ruby
def raw(stringish)
  stringish.to_s.html_safe
end
```

it will force the input into string first. The difference fall into some edge cases, e.g.

```ruby
[1] pry(main)> nil.html_safe()
NoMethodError: undefined method `html_safe' for nil:NilClass
Did you mean?  html_safe?


[7] pry(main)> raw(nil)
=> ""
```

Rails doc recommends that
> To insert something verbatim use the [raw](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html#method-i-raw) helper rather than calling html_safe:

[Read more](https://edgeguides.rubyonrails.org/active_support_core_extensions.html#safe-strings)

2023-06-02 03:06 UTC, mosharaf13 commented on db/seeds.rb
> +  Fabricate(:search_stat)
Thanks for the suggestion. Fixed in 0445058466433648b3c70ff60c29a18007deab3c

2023-06-02 03:16 UTC, mosharaf13 commented on app/models/search_stat.rb
> +  validates :raw_response, presence: true
Initially rows will be created with the column `keyword` only. After scrapping is done it will find rows by id and fill in other columns. So, I should really only validate `:keyword` right?

2023-06-02 04:09 UTC, mosharaf13 commented on db/migrate/20230523085326_create_search_stats.rb
> +      t.references :user, null: false, foreign_key: true
Thanks for the suggestion 👍🏼. Added `non_ad_count`, `top_ad_count`, and `status` column. For the url list of non adword and adword advertisers I am using a separate table in https://github.com/mosharaf13/google-scrapper-ruby/pull/41 PR.

2023-06-02 09:55 UTC, longnd approved these changes

2023-06-02 10:02 UTC, merged