[#11] [UI] As a user, I can list keywords
mosharaf13/google-scrapper-ruby pull request #38
Opened 2023-05-29 07:39 UTC by mosharaf13

Closes #11 

## What happened 👀

- Added table to show search stats 

## Insight 📝

- Used bootstrap table to show search stats for user uploaded keywords.
- Used pagination with 8 items on each page

## Proof Of Work 📹

<details>
<summary>
Table
</summary>

<img width="1392" alt="Screen Shot 2023-05-29 at 2 37 01 PM" src="https://github.com/mosharaf13/google-scrapper-ruby/assets/12990839/8697c5ef-928b-4f20-8291-0fc56cefaa52">
</details>

2023-05-29 11:01 UTC, sanG-github reviewed
Some minor suggestions!! 🚀

2023-05-29 11:01 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +        <% end %>
Why don't we just render the partial (`app/views/search_stats/_search_stat.html.erb`)? It's easier and more convenient. 🚀 

```suggestion
        <%= render @search_stats %>
```

2023-05-29 11:32 UTC, mosharaf13 commented on .gitignore
> +/vendor
Added

2023-05-29 12:30 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +    @pagy, @search_stats = pagy(SearchStat.all, items: 8)
Sorry, I didn't quite understand about the `authorization` section. Can you give a link to read?

2023-05-30 10:59 UTC, sanG-github requested changes
As this is an IC, we should practice following the convention the most.
So, I suggest separating this PR into two dedicated ones.
- #11 
- #14

2023-05-30 11:05 UTC, sanG-github reviewed
Should we handle the blank state for this page? In case there's no resources 😉 
![image](https://github.com/mosharaf13/google-scrapper-ruby/assets/63148598/eb4a5635-52e6-4517-a9c2-4ba369fd24ad)

2023-05-30 11:10 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +    @pagy, @search_stats = pagy(SearchStat.all, items: 8)
The `user_id: 3` should not see the results of the `user_id: 4` and vice versa. 

https://github.com/mosharaf13/google-scrapper-ruby/assets/63148598/0a2d4164-154a-4bb7-9aea-372c084a80e1

2023-05-30 11:12 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +    @pagy, @search_stats = pagy(SearchStat.all, items: 8)
You can take a look at these gems:
- [Pundit](https://github.com/varvet/pundit)
- [Cancancan](https://github.com/CanCanCommunity/cancancan)

2023-05-31 03:48 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +    @pagy, @search_stats = pagy(SearchStat.all, items: 8)
Fixed in 6e67d7957c3a415c53047769fc50b51934acdb06

2023-05-31 04:00 UTC, mosharaf13 commented
> Should we handle the blank state for this page? In case there's no resources 😉 ![image](https://user-images.githubusercontent.com/63148598/241947420-eb4a5635-52e6-4517-a9c2-4ba369fd24ad.png)

Fixed in 4c766755a273b2033b95a7b6ad0cb5db882d5842

2023-05-31 04:05 UTC, mosharaf13 commented
> As this is an IC, we should practice following the convention the most. So, I suggest separating this PR into two dedicated ones.
> 
> * [[UI] As a user, I can list keywords #11](https://github.com/mosharaf13/google-scrapper-ruby/issues/11)
> * [[UI] As a user, I can get keyword search result #14](https://github.com/mosharaf13/google-scrapper-ruby/issues/14)

Should I create separate PR with same commit list or should I cherry pick commits to use in different PR? 

Actually, this was a bit of a mess up. After committing some features about [#14], I realized that I was in [#11]'s branch. As this two issues are quire similar, I thought about creating a PR which resolves both issues.

2023-06-01 07:24 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +    @search_stat.non_adwords_urls = retrieve_non_adwords_urls(@search_stat)
Can we handle it in the Model? This work does not relate to the controller and is more about the business logic.

2023-06-01 07:44 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +  def retrieve_adwords_urls(_search_stat)
I think we don't need the dummy data here, it makes the user more confusing. We need to extract the real ad's URLs instead 😉

2023-06-01 07:44 UTC, sanG-github commented on app/models/search_stat.rb
> +  attr_accessor :adwords_urls, :non_adwords_urls
We need to `sort` the `Model` following [this convention](https://nimblehq.co/compass/development/code-conventions/ruby/ruby-on-rails/#convention-11) 💪

2023-06-01 07:44 UTC, sanG-github commented on config/initializers/pagy.rb
> +require 'pagy/extras/overflow'
Should we move it to line 4? We usually `require` everything we need before using one of those. 🤔

2023-06-01 09:15 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +  def retrieve_adwords_urls(_search_stat)
I added dummy data thinking this PR should mostly deal with UI related stuffs. I have a plan to create a table to store all the links, and I will return the links along with each search stat. Should I add that feature in this PR? or, should I create a separate backend issue?

2023-06-01 11:09 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +  def retrieve_adwords_urls(_search_stat)
Fixed in https://github.com/mosharaf13/google-scrapper-ruby/pull/41

2023-06-01 11:10 UTC, mosharaf13 commented on config/initializers/pagy.rb
> +require 'pagy/extras/overflow'
Fixed in https://github.com/mosharaf13/google-scrapper-ruby/pull/41

2023-06-01 11:10 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +    @search_stat.non_adwords_urls = retrieve_non_adwords_urls(@search_stat)
Fixed in https://github.com/mosharaf13/google-scrapper-ruby/pull/41

2023-06-02 04:23 UTC, mosharaf13 commented on app/controllers/search_stats_controller.rb
> +  def retrieve_adwords_urls(_search_stat)
From your comment, I thought you suggested me to use real data instead of using dummy. So, I created this https://github.com/mosharaf13/google-scrapper-ruby/pull/41 PR where urls are stored in a db, and controller returns urls from there.

About #13. There some works that needs to be done there. I will tackle it in next sprint 💪🏼 .

2023-06-06 07:25 UTC, longnd commented on app/views/search_stats/_raw_response_modal.html.erb
> +  function openRawResponse(rawResponse) {
avoid injecting JS code into the view, follow Nimble's convention here if you plan to use [Vanilla  JS](http://vanilla-js.com/)
https://nimblehq.co/compass/development/code-conventions/javascript/#front-end-js

example from a previous project: https://github.com/nimblehq/braive-web/tree/development/app/assets/javascripts

or a recent project that uses [Stimulus controller](https://stimulus.hotwired.dev/reference/controllers) & Turbo
https://github.com/nimblehq/ewa-payorll-web/tree/develop/app/javascript

2023-06-06 07:25 UTC, longnd commented on app/views/search_stats/_raw_response_modal.html.erb
> +    var backdrop = document.createElement('div');
these steps must be handled by Bootstrap already. Follow their doc should work
https://getbootstrap.com/docs/5.0/components/modal/

2023-06-12 10:12 UTC, sanG-github requested changes
Some last minor suggestions

2023-06-12 10:12 UTC, sanG-github commented on app/models/result_link.rb
> +  enum link_type: { ads_top: 0, non_ads: 2 }
We should better use the `string` for the enum value instead of `integer`, it helps to easier to debug and also read the data from the database.

```suggestion
  enum link_type: { ads_top: 'ads_top', non_ads: 'non_ads' }
```

2023-06-12 10:12 UTC, sanG-github commented on app/models/user.rb
> +  has_many :search_stats, dependent: :destroy
Are we missing the `inverse_of`? 🤔

2023-06-12 10:12 UTC, sanG-github commented on app/views/search_stats/_search_stat.html.erb
> +    <%= button_to 'Show Details', search_stat_path(search_stat), method: :get, class: 'btn btn-primary' %>
We should make the button content localized. 😉 
```suggestion
    <%= button_to t('placeholder.show_button'), search_stat_path(search_stat), method: :get, class: 'btn btn-primary' %>
```

2023-06-12 10:12 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <%= 1 %>
Please remove dummy data 🙇 
```suggestion
            <%= 1 %>
```

2023-06-12 10:12 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <strong><%= SearchStat.human_attribute_name(:total_result_count) %>:</strong>
Instead of duplicating `:` annotation, we can set the content to the `:after` style. ([ref](https://developer.mozilla.org/en-US/docs/Web/CSS/::after))

2023-06-12 10:12 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <%= button_tag 'View Raw Response', class: 'btn btn-primary',
Same here, please make it localized. 😉 
```suggestion
            <%= button_tag 'View Raw Response', class: 'btn btn-primary',
```

2023-06-12 10:12 UTC, sanG-github commented on config/initializers/pagy.rb
> +
```suggestion
```

2023-06-12 10:12 UTC, sanG-github commented on db/migrate/20230601085414_create_result_links.rb
> +    add_index :result_links, :url
Could you please help to elaborate on why we need these indexes? 🙇

2023-06-12 10:12 UTC, sanG-github commented on spec/fabricators/result_link_fabricator.rb
> +  link_type { FFaker.rand 3 }
We should better fabricate it from the model enum 🙌 
```suggestion
  link_type { ResultLink.link_types.keys.sample }
```

2023-06-12 11:30 UTC, mosharaf13 commented on app/views/search_stats/_raw_response_modal.html.erb
> +  function openRawResponse(rawResponse) {
Fixed bd74354cbef789bf45da8ffcb4f509763265ef01

2023-06-12 11:30 UTC, mosharaf13 commented on app/views/search_stats/_raw_response_modal.html.erb
> +    var backdrop = document.createElement('div');
Fixed bd74354cbef789bf45da8ffcb4f509763265ef01

2023-06-12 11:38 UTC, mosharaf13 commented on app/models/user.rb
> +  has_many :search_stats, dependent: :destroy
Fixed 89990de059fb7b5a80641fbc790f6877a0a6ba99

2023-06-12 11:52 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +            <strong><%= SearchStat.human_attribute_name(:total_result_count) %>:</strong>
Should I add custom css for `:` ?

2023-06-12 12:22 UTC, mosharaf13 commented on db/migrate/20230601085414_create_result_links.rb
> +    add_index :result_links, :url
Come to think about it. There's no need really. Removing.

2023-06-12 12:36 UTC, mosharaf13 commented on spec/fabricators/result_link_fabricator.rb
> +  link_type { FFaker.rand 3 }
Fixed d89551c2baf0587728497bdc2cfe9ab94c55db10

2023-06-12 12:36 UTC, mosharaf13 commented on db/migrate/20230601085414_create_result_links.rb
> +    add_index :result_links, :url
Fixed d89551c2baf0587728497bdc2cfe9ab94c55db10

2023-06-12 12:37 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +            <%= button_tag 'View Raw Response', class: 'btn btn-primary',
Fixed 9159302ce281393317c3d78af1c2caac13bc889f

2023-06-12 12:38 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +            <%= 1 %>
Fixed 9159302ce281393317c3d78af1c2caac13bc889f

2023-06-12 12:38 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <%= button_to 'Show Details', search_stat_path(search_stat), method: :get, class: 'btn btn-primary' %>
Fixed 3746cb939a50e7b6c7f3679fe8c23a947428adc1

2023-06-15 10:40 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <strong><%= SearchStat.human_attribute_name(:total_result_count) %>:</strong>
I mean, you can define a custom class for the title.
And then apply this style for the title only -> then, it will automatically append the `:` after the title text.

2023-06-16 04:19 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +            <strong><%= SearchStat.human_attribute_name(:total_result_count) %>:</strong>
Fixed in 8730d24f608075e0a38eb61c9f9401edfe1ffaa1

2023-06-16 06:22 UTC, longnd reviewed
Do you intend to write tests in another PR?

2023-06-16 06:22 UTC, longnd commented on app/assets/stylesheets/components/search_stat_details.scss
> +.title::after {
This is not a front-end IC, but if you want to follow Nimble's convention (this CSS component is following that convention), this naming convention is incorrect.

Note that the file name is `search_stat_details.scss` so it should define a component named `search-start-detail`
https://nimblehq.co/compass/development/code-conventions/css/#convention-28

also check this convention https://nimblehq.co/compass/development/web/user-interface/ on how to scope UI elements
an example from another project:
https://github.com/nimblehq/mia-web/blob/development/app/assets/stylesheets/components/_card-group.scss

```suggestion
.search-stat-detail {
  .search-stat-detail__title:after {
   ...
  }
}
```

2023-06-16 06:22 UTC, longnd commented on app/javascript/components/raw_response_modal.js
this file should be named `index.js` and placed under the `raw_response_model` directory, i.e.
`app/javascript/components/raw_response_modal/index.js`.

2023-06-16 06:22 UTC, longnd commented on app/javascript/components/raw_response_modal.js
once again, this is not a front-end IC so this comment can be skipped, but if you want to follow Nimble convention here
https://nimblehq.co/compass/development/code-conventions/javascript/#convention-41

and example from previous project
https://github.com/nimblehq/mia-web/tree/development/app/assets/javascripts/components

2023-06-16 06:22 UTC, longnd commented on app/javascript/components/raw_response_modal.js
> +function openRawResponse(rawResponse) {
relates to the previous comment, component should be defined by a classhttps://nimblehq.co/compass/development/code-conventions/javascript/#convention-43

2023-06-16 06:22 UTC, longnd commented on app/views/search_stats/_search_stat.html.erb
> +    <%= button_to t('buttons.search_stat_details'), search_stat_path(search_stat), method: :get, class: 'btn btn-primary' %>
Do you have special intention when creating a button? Note that the `button_to` tag will generate a form with a button to submit.

It is semantically incorrect to link to another page that way, a link is the best choice, no?
```suggestion
    <%= link_to t('search_stat_details`), search_stat_path(search_stat), class: 'btn btn-primary' %>
```

2023-06-16 06:22 UTC, longnd commented on app/views/search_stats/show.html.erb
> +          </p>
pls use the tag in a semantically way
https://nimblehq.co/compass/development/code-conventions/html/#convention-10

the `<p>` tag should be used for a paragraph of text. In this case, there is no need to wrap the button in a `<p>` tag.

2023-06-16 06:22 UTC, longnd commented on app/views/search_stats/show.html.erb
> +          </p>
I still don't get the reason why use need to write custom JS code to initialize the modal? Since this is a default bootstrap modal, it should work out of the box, without any custom JS code:

```suggestion
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#rawResponseModal">
              View Raw Response
            </button>
          </p>

          <!-- Modal -->
          <div class="modal fade" id="rawResponseModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <%== @search_stat.raw_response %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>
```

2023-06-16 06:22 UTC, longnd commented on app/javascript/components/raw_response_modal.js
> +function openRawResponse(rawResponse) {
but all of these custom JS code is redundant. The modal should work without these code. Pls check the bellow comment.

2023-06-16 06:22 UTC, longnd commented on app/views/search_stats/show.html.erb
> +      <h5 class="card-title">List of URLs of AdWords Advertisers in Top Position</h5>
If you want to support localization, let's be consistent, this sentence should be localized as well.

2023-06-16 08:06 UTC, sanG-github reviewed
Last round of reviews. We're getting there. 😉

2023-06-16 08:06 UTC, sanG-github commented on app/views/search_stats/index.html.erb
> +      <p class="mb-0">No search stats found.</p>
As Long commented, messages like that should be localized as well, for consistency 😉 
Please help to check other places.

2023-06-16 08:06 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +        <% @search_stat.result_links.ads_top.or(@search_stat.result_links.non_ads).each do |result_link| %>
We need to retrieve all the `ads_top` links, right? 🙈 

```suggestion
        <% @search_stat.result_links.ads_top.each do |result_link| %>
```

2023-06-16 08:06 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <%= link_to result_link.url, result_link.url %>
What happens if we redirect the user to another page in case of the Ads link, and open a new tab in case of the Non-ads link? It's not consistent, no? 😭 

```suggestion
            <%= link_to result_link.url, result_link.url, target: '_blank' %>
```

2023-06-16 08:06 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +            <%= link_to result_link.url, result_link.url, target: "_blank" %>
Single quote for Ruby code ✨ 
```suggestion
            <%= link_to result_link.url, result_link.url, target: '_blank' %>
```

2023-06-16 08:06 UTC, sanG-github commented on app/views/search_stats/show.html.erb
> +<%= render 'raw_response_modal' %>
We need more indent. 😜 
```suggestion
  <%= render 'raw_response_modal' %>
```

2023-06-16 08:06 UTC, sanG-github commented on config/locales/en.yml
> +    raw_response: View Raw Response
Alphabetical order ✨ 
```suggestion
    raw_response: View Raw Response
    search_stat_details: Show Details
```

2023-06-16 08:06 UTC, sanG-github commented on db/seeds.rb
> +user = User.where(email: 'user@demo.com').first_or_create(Fabricate.attributes_for(:user, email: 'user@demo.com'))
Should we do it explicitly with [find_or_initialize_by](https://kevinjmurphy.com/posts/find-or-initialize-by-block/#initial-impressions)
```ruby
user = User.find_or_initialize_by(email: 'user@demo.com') do |user|
  user.password = 'xxxx'
end
```

2023-06-19 02:33 UTC, mosharaf13 commented on app/models/result_link.rb
> +  enum link_type: { ads_top: 0, non_ads: 2 }
Fixed in d89551c2baf0587728497bdc2cfe9ab94c55db10

2023-06-19 04:34 UTC, mosharaf13 commented on app/assets/stylesheets/components/search_stat_details.scss
> +.title::after {
Fixed in f3170c0501d44d7457d6f3b1933a84dc503da118

2023-06-19 04:59 UTC, mosharaf13 commented on app/javascript/components/raw_response_modal.js
Fixed in 807967188578112fd3049d50e048c99a83e2d62f

2023-06-19 05:05 UTC, mosharaf13 commented on app/views/search_stats/_search_stat.html.erb
> +    <%= button_to t('buttons.search_stat_details'), search_stat_path(search_stat), method: :get, class: 'btn btn-primary' %>
Fixed in 78e96e53bc4ca3a1177dd631c17def958195bbf7

2023-06-19 05:25 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +          </p>
Fixed in f895479d94881f752f3ce49807f183db534ebc53

2023-06-19 05:31 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +      <h5 class="card-title">List of URLs of AdWords Advertisers in Top Position</h5>
Fixed in 055a969b21ebddfd965f767c79e02c0fdf7de979

2023-06-19 06:02 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +          </p>
I didn't realize there was a way to set iframe srcdoc directly using rails. Thought I needed javascript for that.

Fixed in 51725d55ade6f598c7bab4067416eaaa18b32cca

2023-06-19 06:07 UTC, mosharaf13 commented on app/views/search_stats/index.html.erb
> +      <p class="mb-0">No search stats found.</p>
Fixed in 5bf2a10213c512bb303f48d3fcc154488b9fa38c

2023-06-19 06:10 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +        <% @search_stat.result_links.ads_top.or(@search_stat.result_links.non_ads).each do |result_link| %>
Oh no. What was I thinking 😬. Thanks for noticing. Fixed in 70600016a18c03971815b73f136cc111d85c7a65

2023-06-19 06:15 UTC, mosharaf13 commented on config/locales/en.yml
> +    raw_response: View Raw Response
Fixed in 7ea292090c3620e45e3159d7233806e5f545ec12

2023-06-19 06:19 UTC, mosharaf13 commented on db/seeds.rb
> +user = User.where(email: 'user@demo.com').first_or_create(Fabricate.attributes_for(:user, email: 'user@demo.com'))
Yeah, this one looks more explicit. Thanks for the suggestion. Fixed in d4b5083f5b15c30828b429d6c5b92292ed29e7ba

2023-06-19 10:00 UTC, mosharaf13 commented
> Do you intend to write tests in another PR?

Yes. As this PR already covers a lot ( a bit more than it should have ), I am thinking about opening another issue that covers tests.

2023-06-20 08:17 UTC, mosharaf13 commented on app/javascript/components/raw_response_modal.js
> +function openRawResponse(rawResponse) {
Removed js file. Now handling it using bootstrap.

2023-06-20 09:16 UTC, sanG-github approved these changes

2023-06-20 09:16 UTC, sanG-github commented on app/assets/stylesheets/application.scss
> +@import './components/search_stat_details'
Add an empty line after each section.

```suggestion
@import './components/search_stat_details'

```

2023-06-20 09:16 UTC, sanG-github commented on app/controllers/search_stats_controller.rb
> +    @search_stat = SearchStat.includes(:result_links).find(params[:id])
Authorization 😉 The user can provide the `id` of other's search stat.

```suggestion
    @search_stat = current_user.search_stats.includes(:result_links).find(params[:id])
```

2023-06-20 09:16 UTC, sanG-github commented on app/views/search_stats/_raw_response_modal.html.erb
> +        <iframe style="width: 100%; height: 80vh; border: none;" srcdoc="<%= sanitize(@search_stat.raw_response) %>" >
We prefer separating the CSS from the in-line styles -> But in this case, I will let you choose. 😉

2023-06-22 04:38 UTC, mosharaf13 commented on app/views/search_stats/show.html.erb
> +<%= render 'raw_response_modal' %>
Fixed in 7c64ab67da1bef63be96cb39f761931851712988

2023-06-22 05:43 UTC, mosharaf13 commented on app/views/search_stats/_raw_response_modal.html.erb
> +        <iframe style="width: 100%; height: 80vh; border: none;" srcdoc="<%= sanitize(@search_stat.raw_response) %>" >
Fixed in e896cb48d93afc28206bab0f8931cdec86e3fcbb

2023-06-22 15:24 UTC, longnd approved these changes

2023-06-22 15:24 UTC, longnd commented on app/views/search_stats/_raw_response_modal.html.erb
> +        <iframe srcdoc="<%= sanitize(@search_stat.raw_response) %>" >
I'm aware that you want to be safe, but in our use case, we're trying to render the content scrapped from Google as-is. Sanitize() will strip all but known-safe tags and attributes. The result may not look as what we expected. 

Let's check if after having actual scrapped content.

2023-06-23 03:42 UTC, merged